import { Platform, StyleSheet } from 'react-native';

export default function createStyles(theme) {
    const c = theme.colors;

    return StyleSheet.create({
        headerRightSpacer: {
            width: 40,
        },
        scrollContent: {
            padding: 24,
            paddingBottom: 120,
        },
        form: {
            gap: 25,
        },
        section: {
            gap: 12,
        },
        descriptionInput: {
            height: 100,
        },
        locationCard: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: c.surfaceMuted,
            borderRadius: 12,
            padding: 16,
            borderWidth: 1,
            borderColor: c.border,
        },
        locationCardActive: {
            borderColor: c.accent,
            backgroundColor: c.surfaceMuted,
        },
        locationIcon: {
            width: 44,
            height: 44,
            borderRadius: 22,
            backgroundColor: c.border,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 16,
        },
        locationIconActive: {
            backgroundColor: c.accent,
        },
        locationInfo: {
            flex: 1,
        },
        locationTitle: {
            fontSize: 15,
            fontWeight: '600',
            color: c.textPrimary,
        },
        locationSub: {
            fontSize: 13,
            color: c.iconMuted,
            marginTop: 2,
        },
        locationStreet: {
            fontSize: 15,
            fontWeight: '600',
            color: c.textPrimary,
        },
        locationCity: {
            fontSize: 14,
            color: c.textMuted,
            marginTop: 2,
        },
        locationCoords: {
            fontSize: 11,
            color: c.iconSubtle,
            marginTop: 4,
            fontVariant: ['tabular-nums'],
        },
        locationChevron: {
            marginLeft: 8,
        },
        footer: {
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            backgroundColor: c.bg,
            borderTopWidth: 1,
            borderTopColor: c.border,
            padding: 24,
            paddingBottom: Platform.OS === 'ios' ? 40 : 24,
        },
        submitButton: {
            backgroundColor: c.accent,
            borderRadius: 12,
            padding: 18,
            alignItems: 'center',
            shadowColor: c.accent,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
            elevation: 8,
        },
        submitButtonText: {
            color: c.accentContrast,
            fontSize: 18,
            fontWeight: '600',
        },
        disabledButton: {
            opacity: 0.7,
        },
        modalContainer: {
            flex: 1,
            backgroundColor: c.bg,
        },
        modalTopBar: {
            backgroundColor: c.bg,
            borderBottomWidth: 1,
            borderBottomColor: c.border,
            paddingHorizontal: 20,
            paddingBottom: 14,
            paddingTop: 10,
            alignItems: 'center',
        },
        modalTitle: {
            fontSize: 16,
            fontWeight: '700',
            color: c.textPrimary,
        },
        modalSubtitle: {
            fontSize: 12,
            color: c.iconSubtle,
            marginTop: 3,
        },
        mapWrapper: {
            flex: 1,
            position: 'relative',
        },
        crosshairContainer: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            justifyContent: 'center',
            alignItems: 'center',
        },
        crosshairShadow: {
            position: 'absolute',
            width: 20,
            height: 6,
            borderRadius: 10,
            backgroundColor: 'rgba(0,0,0,0.25)',
            bottom: '50%',
            marginBottom: -3,
        },
        crosshairStem: {
            position: 'absolute',
            width: 3,
            height: 22,
            backgroundColor: c.accent,
            borderRadius: 2,
            bottom: '50%',
            marginBottom: 12,
        },
        crosshairHead: {
            position: 'absolute',
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: c.accent,
            bottom: '50%',
            marginBottom: 30,
            justifyContent: 'center',
            alignItems: 'center',
            shadowColor: c.accent,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.5,
            shadowRadius: 8,
            elevation: 6,
        },
        crosshairInner: {
            width: 10,
            height: 10,
            borderRadius: 5,
            backgroundColor: c.accentContrast,
        },
        modalBottomBar: {
            backgroundColor: c.bg,
            borderTopWidth: 1,
            borderTopColor: c.border,
        },
        modalActions: {
            flexDirection: 'row',
            gap: 12,
            paddingHorizontal: 20,
            paddingVertical: 16,
        },
        modalCancelBtn: {
            flex: 1,
            borderRadius: 12,
            paddingVertical: 16,
            alignItems: 'center',
            backgroundColor: c.surfaceMuted,
            borderWidth: 1,
            borderColor: c.border,
        },
        modalCancelText: {
            fontSize: 15,
            fontWeight: '600',
            color: c.textMuted,
        },
        modalConfirmBtn: {
            flex: 2,
            borderRadius: 12,
            paddingVertical: 16,
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'center',
            backgroundColor: c.accent,
            shadowColor: c.accent,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
            elevation: 8,
        },
        modalConfirmText: {
            fontSize: 15,
            fontWeight: '700',
            color: c.accentContrast,
        },
        categoryCard: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingVertical: 14,
        },
        categorySelected: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
            flex: 1,
        },
        categorySelectedText: {
            fontSize: 16,
            color: c.textPrimary,
        },
        categoryPlaceholder: {
            fontSize: 16,
            color: c.iconSubtle,
            flex: 1,
        },
        categoryGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            padding: 16,
            gap: 12,
        },
        categoryGridItem: {
            width: '30%',
            aspectRatio: 1,
            backgroundColor: c.surfaceMuted,
            borderRadius: 14,
            borderWidth: 1,
            borderColor: c.border,
            justifyContent: 'center',
            alignItems: 'center',
            gap: 8,
            padding: 8,
        },
        categoryGridItemActive: {
            borderColor: c.accent,
            backgroundColor: c.accentSurfaceStrong,
        },
        categoryGridLabel: {
            fontSize: 11,
            color: c.textMuted,
            textAlign: 'center',
        },
        categoryGridLabelActive: {
            color: c.accent,
            fontWeight: '600',
        },
    });
}
