import { Platform, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    headerRightSpacer: {
        width: 40,
    },
    scrollContent: {
        padding: 24,
        paddingBottom: 120,
    },
    form: {
        gap: 25,
    },
    section: {
        gap: 12,
    },
    label: {
        fontSize: 18,
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: 4,
    },
    input: {
        backgroundColor: '#1a1a1a',
        borderRadius: 10,
        padding: 16,
        color: '#ffffff',
        borderWidth: 1,
        borderColor: '#2a2a2a',
        fontSize: 16,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#2a2a2a',
        paddingHorizontal: 16,
    },
    inputInner: {
        flex: 1,
        paddingVertical: 16,
        fontSize: 16,
        color: '#ffffff',
    },
    currencyPrefix: {
        fontSize: 16,
        color: '#aaa',
        marginRight: 4,
    },
    unitSuffix: {
        fontSize: 14,
        color: '#666',
    },
    textArea: {
        height: 120,
        textAlignVertical: 'top',
    },
    row: {
        flexDirection: 'row',
    },
    locationCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#2a2a2a',
    },
    locationCardActive: {
        borderColor: '#6366f1',
        backgroundColor: '#1a1a1a',
    },
    locationIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#2a2a2a',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    locationIconActive: {
        backgroundColor: '#6366f1',
    },
    locationInfo: {
        flex: 1,
    },
    locationTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#ffffff',
    },
    locationSub: {
        fontSize: 13,
        color: '#888',
        marginTop: 2,
    },
    locationStreet: {
        fontSize: 15,
        fontWeight: '600',
        color: '#ffffff',
    },
    locationCity: {
        fontSize: 14,
        color: '#aaa',
        marginTop: 2,
    },
    locationCoords: {
        fontSize: 11,
        color: '#555',
        marginTop: 4,
        fontVariant: ['tabular-nums'],
    },
    locationChevron: {
        marginLeft: 8,
    },
    locationErrorText: {
        color: '#ef4444',
        fontSize: 12,
        marginTop: -2,
        fontWeight: '500',
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#0a0a0a',
        borderTopWidth: 1,
        borderTopColor: '#2a2a2a',
        padding: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    },
    submitButton: {
        marginTop: 0,
        backgroundColor: '#6366f1',
        borderRadius: 12,
        padding: 18,
        alignItems: 'center',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 8,
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
    },
    disabledButton: {
        opacity: 0.7,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#0a0a0a',
    },
    modalTopBar: {
        backgroundColor: '#0a0a0a',
        borderBottomWidth: 1,
        borderBottomColor: '#2a2a2a',
        paddingHorizontal: 20,
        paddingBottom: 14,
        paddingTop: 10,
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#ffffff',
    },
    modalSubtitle: {
        fontSize: 12,
        color: '#666',
        marginTop: 3,
    },
    mapWrapper: {
        flex: 1,
        position: 'relative',
    },
    // ── Centre-pin crosshair ──────────────────────────────────────────────
    crosshairContainer: {
        position: 'absolute',
        top: 0, left: 0, right: 0, bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    crosshairShadow: {
        position: 'absolute',
        width: 20, height: 6, borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.25)',
        bottom: '50%',
        marginBottom: -3,
    },
    crosshairStem: {
        position: 'absolute',
        width: 3, height: 22,
        backgroundColor: '#6366f1',
        borderRadius: 2,
        bottom: '50%',
        marginBottom: 12,
    },
    crosshairHead: {
        position: 'absolute',
        width: 32, height: 32, borderRadius: 16,
        backgroundColor: '#6366f1',
        bottom: '50%',
        marginBottom: 30,
        justifyContent: 'center', alignItems: 'center',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
        elevation: 6,
    },
    crosshairInner: {
        width: 10, height: 10, borderRadius: 5,
        backgroundColor: '#fff',
    },
    modalBottomBar: {
        backgroundColor: '#0a0a0a',
        borderTopWidth: 1,
        borderTopColor: '#2a2a2a',
    },
    modalActions: {
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
    modalCancelBtn: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        borderWidth: 1,
        borderColor: '#2a2a2a',
    },
    modalCancelText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#aaa',
    },
    modalConfirmBtn: {
        flex: 2,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 8,
    },
    modalConfirmText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#fff',
    },
    // ── Category picker ──────────────────────────────────────────────────────
    categoryCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
    },
    categorySelected: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flex: 1,
    },
    categorySelectedText: {
        fontSize: 16,
        color: '#ffffff',
    },
    categoryPlaceholder: {
        fontSize: 16,
        color: '#666',
        flex: 1,
    },
    categoryGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding: 16,
        gap: 12,
    },
    categoryGridItem: {
        width: '30%',
        aspectRatio: 1,
        backgroundColor: '#1a1a1a',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#2a2a2a',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        padding: 8,
    },
    categoryGridItemActive: {
        borderColor: '#6366f1',
        backgroundColor: '#1e1b4b',
    },
    categoryGridLabel: {
        fontSize: 11,
        color: '#aaa',
        textAlign: 'center',
    },
    categoryGridLabelActive: {
        color: '#818cf8',
        fontWeight: '600',
    },
});

export default styles;

