import { StyleSheet } from 'react-native';

export default function createStyles(theme) {
    return StyleSheet.create({
        topNav: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingTop: 10,
        },
        backButton: {
            width: 40,
            height: 40,
            justifyContent: 'center',
        },
        scrollContent: {
            paddingHorizontal: 20,
            paddingBottom: 110,
        },
        header: {
            alignItems: 'center',
            paddingVertical: 10,
        },
        avatarContainer: {
            position: 'relative',
            marginBottom: 15,
            marginTop: 10,
            alignItems: 'center',
        },
        avatar: {
            width: 110,
            height: 110,
            borderRadius: 55,
            backgroundColor: theme.colors.surfaceMuted,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 3,
            borderColor: theme.colors.borderStrong,
        },
        avatarText: {
            fontSize: 42,
            fontWeight: 'bold',
            color: theme.colors.accent,
        },
        editAvatarButton: {
            position: 'absolute',
            top: 0,
            right: 0,
            backgroundColor: theme.colors.surfaceMuted,
            borderRadius: 15,
            width: 32,
            height: 32,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1.5,
            borderColor: theme.colors.borderStrong,
        },
        verifiedBadgeContainer: {
            position: 'absolute',
            bottom: 2,
            right: 2,
            backgroundColor: theme.colors.bg,
            borderRadius: 15,
            padding: 2,
        },
        name: {
            fontSize: 26,
            fontWeight: '700',
            color: theme.colors.textPrimary,
            marginBottom: 6,
        },
        contactInfo: {
            alignItems: 'flex-start',
            marginBottom: 10,
        },
        contactRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            marginBottom: 6,
        },
        contactText: {
            fontSize: 14,
            color: theme.colors.textMuted,
            marginLeft: 8,
        },
        contactActionText: {
            fontSize: 14,
            color: theme.colors.accent,
            marginLeft: 8,
            fontWeight: '600',
        },
        statsContainer: {
            flexDirection: 'row',
            backgroundColor: theme.colors.surface,
            borderRadius: 16,
            paddingVertical: 20,
            marginTop: 10,
            marginBottom: 30,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        statBox: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
        },
        statDivider: {
            width: 1,
            backgroundColor: theme.colors.rowDivider,
        },
        statValue: {
            fontSize: 22,
            fontWeight: '700',
            color: theme.colors.textPrimary,
            marginBottom: 6,
        },
        statLabel: {
            fontSize: 14,
            color: theme.colors.textMuted,
            fontWeight: '500',
        },
        menuContainer: {
            backgroundColor: theme.colors.surface,
            borderRadius: 16,
            paddingVertical: 10,
            marginBottom: 30,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        menuItem: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 16,
            paddingHorizontal: 20,
        },
        menuIconContainer: {
            width: 32,
            justifyContent: 'center',
            alignItems: 'flex-start',
        },
        menuItemText: {
            flex: 1,
            fontSize: 16,
            color: theme.colors.textSecondary,
            fontWeight: '500',
        },
        logoutContainer: {
            backgroundColor: theme.colors.surface,
            borderRadius: 16,
            paddingVertical: 4,
            marginBottom: 30,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        logoutItem: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 16,
            paddingHorizontal: 20,
        },
        logoutText: {
            flex: 1,
            fontSize: 16,
            color: theme.colors.danger,
            fontWeight: 'bold',
        },
    });
}
