import { StyleSheet } from 'react-native';

export default function createStyles(theme) {
    const c = theme.colors;
    return {
        styles: StyleSheet.create({
            loaderContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
            topLoader: { paddingVertical: 10, alignItems: 'center' },
            headerContainer: { padding: 20, paddingBottom: 10 },
            screenTitle: { fontSize: 28, fontWeight: 'bold', color: c.textPrimary, marginBottom: 20 },
            segmentedControl: {
                flexDirection: 'row',
                backgroundColor: c.surfaceMuted,
                borderRadius: 12,
                padding: 4,
                borderWidth: 1,
                borderColor: c.border,
            },
            segment: {
                flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
                paddingVertical: 10, borderRadius: 10, gap: 6,
            },
            activeSegment: { backgroundColor: c.accent },
            segmentText: { color: c.iconMuted, fontWeight: '600', fontSize: 14 },
            activeSegmentText: { color: c.accentContrast, fontWeight: 'bold' },
            listContainer: { padding: 20, paddingTop: 10, paddingBottom: 100, flexGrow: 1 },
            card: {
                backgroundColor: c.surfaceMuted,
                borderRadius: 16,
                padding: 16,
                marginBottom: 16,
                borderWidth: 1,
                borderColor: c.border,
            },
            cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
            toolIcon: {
                width: 48, height: 48, borderRadius: 12,
                backgroundColor: `${c.accent}18`,
                justifyContent: 'center', alignItems: 'center',
                marginRight: 12,
            },
            headerInfo: { flex: 1 },
            toolName: { fontSize: 16, fontWeight: 'bold', color: c.textPrimary, marginBottom: 4 },
            otherParty: { fontSize: 12, color: c.iconMuted },
            statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, maxWidth: 130 },
            statusText: { fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
            divider: { height: 1, backgroundColor: c.border, marginBottom: 16 },
            detailsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
            dateInfo: { alignItems: 'center' },
            dateArrow: { paddingHorizontal: 10 },
            dateLabel: { fontSize: 10, color: c.iconSubtle, marginBottom: 2, textTransform: 'uppercase' },
            dateValue: { fontSize: 13, color: c.textSecondary, fontWeight: '500' },
            priceInfo: {
                alignItems: 'flex-end',
                borderLeftWidth: 1,
                borderLeftColor: c.border,
                paddingLeft: 16,
            },
            priceLabel: { fontSize: 10, color: c.iconSubtle, marginBottom: 2, textTransform: 'uppercase' },
            priceValue: { fontSize: 16, color: c.accent, fontWeight: 'bold' },
            metaSection: { marginBottom: 10 },
            metaLabel: { color: c.iconMuted, fontSize: 11, textTransform: 'uppercase', marginBottom: 2, letterSpacing: 0.4 },
            metaValue: { color: c.textPrimary, fontSize: 14, fontWeight: '600' },
            metaNote: { color: c.textSecondary, fontSize: 13, lineHeight: 19 },
            actions: { flexDirection: 'row', gap: 12, marginTop: 8 },
            actionButton: { flex: 1, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
            approveButton: { backgroundColor: c.success },
            rejectButton: {
                backgroundColor: `${c.danger}18`,
                borderWidth: 1,
                borderColor: c.danger,
            },
            approveButtonText: { color: c.accentContrast, fontWeight: 'bold', fontSize: 14 },
            rejectButtonText: { color: c.danger, fontWeight: 'bold', fontSize: 14 },
            cancelLink: { alignSelf: 'center', paddingVertical: 8, marginTop: 4 },
            cancelLinkText: { color: c.iconSubtle, fontSize: 12, textDecorationLine: 'underline' },
            payNowButton: { marginTop: 10 },
            emptyContainer: { marginTop: 60, alignItems: 'center', padding: 40, flex: 1 },
            emptyTitle: { fontSize: 18, fontWeight: 'bold', color: c.textPrimary, marginTop: 10, marginBottom: 8 },
            emptyText: { color: c.iconMuted, fontSize: 15, textAlign: 'center', lineHeight: 22 },
        }),

        C: {
            accent: c.accent,
            success: c.success,
            danger: c.danger,
            warning: c.warning,
            muted: c.iconMuted,
        },
    };
}
