import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#0a0a0a',
    },
    topLoader: {
        paddingVertical: 10,
        alignItems: 'center',
    },
    header: {
        paddingHorizontal: 20,
        paddingTop: 15,
        paddingBottom: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'rgba(10, 10, 10, 0.8)',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#ffffff',
    },
    listContainer: {
        padding: 15,
        paddingBottom: 100,
        flexGrow: 1,
    },
    card: {
        backgroundColor: '#1a1a1a',
        borderRadius: 20,
        marginBottom: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#2a2a2a',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.4,
        shadowRadius: 15,
    },
    imagePlaceholder: {
        height: 200,
        backgroundColor: '#2a2a2a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imagePlaceholderText: {
        color: '#555',
        fontSize: 16,
        fontWeight: '600',
    },
    cardContent: {
        padding: 18,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 6,
    },
    toolName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#ffffff',
        flex: 1,
        marginRight: 10,
    },
    price: {
        fontSize: 20,
        fontWeight: '800',
        color: '#818cf8',
    },
    perDay: {
        fontSize: 12,
        color: '#666',
        fontWeight: 'normal',
    },
    category: {
        fontSize: 13,
        color: '#6366f1',
        marginBottom: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    description: {
        fontSize: 14,
        color: '#999',
        marginBottom: 16,
        lineHeight: 22,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#262626',
        paddingTop: 15,
    },
    ownerText: {
        fontSize: 12,
        color: '#666',
        fontWeight: '500',
    },
    verifiedBadge: {
        backgroundColor: 'rgba(34, 197, 94, 0.15)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: 'rgba(34, 197, 94, 0.2)',
    },
    verifiedText: {
        color: '#4ade80',
        fontSize: 11,
        fontWeight: '700',
    },
    emptyContainer: {
        marginTop: 60,
        alignItems: 'center',
        paddingHorizontal: 40,
        flex: 1,
    },
    emptyIconContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(99, 102, 241, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    emptyTitle: {
        color: '#fff',
        fontSize: 22,
        fontWeight: '800',
        marginBottom: 12,
        letterSpacing: -0.5,
    },
    emptyText: {
        color: '#888',
        fontSize: 15,
        textAlign: 'center',
        marginBottom: 35,
        lineHeight: 22,
    },
    swipeDownToRefreshContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        opacity: 0.8,
    },
    swipeDownToRefreshText: {
        color: '#6366f1',
        fontWeight: '600',
        fontSize: 14,
        letterSpacing: 0.5,
    },
});

export default styles;
